"""Mudar nome da coluna Text para Content na Tabela Text

Revision ID: 2ed21e6d3f5c
Revises: 6c538e980380
Create Date: 2025-10-20 12:16:49.912829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed21e6d3f5c'
down_revision: Union[str, Sequence[str], None] = '6c538e980380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
