"""Mudar nome da coluna Text para Content na Tabela Text

Revision ID: 5d7c3d1ab3dc
Revises: 2ed21e6d3f5c
Create Date: 2025-10-20 12:17:50.796494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d7c3d1ab3dc'
down_revision: Union[str, Sequence[str], None] = '2ed21e6d3f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('text', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('text', mysql.TEXT(), nullable=True))
    op.drop_column('text', 'content')
    # ### end Alembic commands ###
