"""Mudança nome coluna number - Tabela Client

Revision ID: 787508f8aeef
Revises: ab11a8ab77ad
Create Date: 2025-10-12 16:22:36.729798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787508f8aeef'
down_revision: Union[str, Sequence[str], None] = 'ab11a8ab77ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
