"""Name column SliderImage Table

Revision ID: a4c871b43227
Revises: 5d7c3d1ab3dc
Create Date: 2025-10-26 14:10:04.746700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a4c871b43227'
down_revision: Union[str, Sequence[str], None] = '5d7c3d1ab3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('url_image', sa.String(length=255), nullable=False))
    op.drop_column('service', 'image_url')
    op.add_column('sliderimage', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sliderimage', 'name')
    op.add_column('service', sa.Column('image_url', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('service', 'url_image')
    # ### end Alembic commands ###
