"""Criar Tabelas

Revision ID: db22ff05a82e
Revises: 
Create Date: 2025-09-29 14:33:13.397246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db22ff05a82e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    op.drop_table('admin')
    op.add_column('producttype', sa.Column('has_producer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producttype', 'has_producer')
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('reset_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('reset_expires_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text',
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('text', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('page', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
